#!/bin/bash -eux

usage() {
  echo "Usage: $0" 1>&2
  exit 1
}

DIR="$( cd "$(dirname "$0")" ; pwd -P )"
export CUSTOM_COMPILE_COMMAND="$(basename "$0")"

if [ "$#" -eq 0 ] ; then
    python2 "${DIR}/tools/compile.par" --allow-unsafe --output-file="${DIR}/src/requirements.txt" "${DIR}/src/requirements.in"
    python2 "${DIR}/tools/compile.par" --allow-unsafe --output-file="${DIR}/tests/requirements.txt" "${DIR}/tests/requirements.in"

    python3 "${DIR}/tools/compile.par" --allow-unsafe --output-file="${DIR}/src/requirements3.txt" "${DIR}/src/requirements.in"
    python3 "${DIR}/tools/compile.par" --allow-unsafe --output-file="${DIR}/tests/requirements3.txt" "${DIR}/tests/requirements.in"
    bazel test //... --test_output=errors
    bazel build //src/...
    install $(bazel info bazel-bin)/src/*.par tools/
else
  usage
fi
