local_repository(
    name = "com_github_ali5h_rules_pip",
    path = "..",
)

load("@com_github_ali5h_rules_pip//:defs.bzl", "pip_import")

pip_import(
    name = "piptool_deps_tests_3",
    compile = False,
    python_interpreter = "python3",
    requirements = "//tests:requirements.txt",
)

load(
    "@piptool_deps_tests_3//:requirements.bzl",
    "pip_install",
)

# pip_install acts like pip install command and can accept arguments
pip_install([
    "--only-binary",
    ":all",
])
