load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Download the rules_docker repository at release v0.13.0
http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "4521794f0fba2e20f3bf15846ab5e01d5332e587e9ce81629c7f96c793bb7036",
    strip_prefix = "rules_docker-0.14.4",
    urls = ["https://github.com/bazelbuild/rules_docker/releases/download/v0.14.4/rules_docker-v0.14.4.tar.gz"],
)

load(
    "@io_bazel_rules_docker//repositories:repositories.bzl",
    container_repositories = "repositories",
)

container_repositories()

load("@io_bazel_rules_docker//repositories:deps.bzl", container_deps = "deps")

container_deps()

load("@io_bazel_rules_docker//repositories:pip_repositories.bzl", "pip_deps")

pip_deps()

load(
    "@io_bazel_rules_docker//container:container.bzl",
    "container_pull",
)

container_pull(
    name = "py3_image_base",
    digest = "sha256:168896be6346aef393bb0cfd0878422a8b9efb7d31f72326a30b6ab59dfcdb6e",
    registry = "gcr.io",
    repository = "distroless/python3-debian10",
)

load(
    "@io_bazel_rules_docker//python3:image.bzl",
    _py_image_repos = "repositories",
)

_py_image_repos()

local_repository(
    name = "com_github_ali5h_rules_pip",
    path = "..",
)

load("@com_github_ali5h_rules_pip//:defs.bzl", "pip_import")

pip_import(
    name = "piptool_deps_tests_3",
    timeout = 1200,
    compile = False,
    python_interpreter = "python3.8",
    requirements = "//tests:requirements.txt",
)

load(
    "@piptool_deps_tests_3//:requirements.bzl",
    "pip_install",
)

# pip_install acts like pip install command and can accept arguments
pip_install([
    "--only-binary",
    ":all",
    "--platform",
    "manylinux1_x86_64",
])

load("@com_github_ali5h_rules_pip//third_party/cpython:configure.bzl", "python_configure")

python_configure(
    name = "cpython",
    devel = True,
    interpreter = "python3.8",
)

# added at the end to not override rules_docker
register_toolchains(
    "@//:toolchain",
)
